### ISSUE TITLE
Insert email address into [INSERT EMAIL ADDRESS]

### ISSUE THREAD

**Issue by jtdoepke** [mintel/repo-boilerplate#3]
The `CONTRIBUTING.md` file has a `[INSERT EMAIL ADDRESS]` bit. We should create/pick a public email address for our GitHub presence.

**Comment by nabadger** [comment]
Agree - I'll follow up on this with Sam/Matt/Infra.

**Comment by nabadger** [comment]
Closing this - @trickv doesn't think we need this right now.
