### ISSUE TITLE
Split CONTRIBUTING.md to CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by jtdoepke** [mintel/repo-boilerplate#5]
Most of `CONTRIBUTING.md` is code of conduct stuff, which is not what I would expect to find in there. Pytest [has a good example](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst).

**Comment by nabadger** [comment]
Done - contirbuting.md will need updates (I'll create an issue for that).
